version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: projeto_queijosFinos
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  jaeger-api:
    image: jaegertracing/opentelemetry-all-in-one
    container_name: jaeger-api
    ports:
      - 16686:16686
    depends_on:
      - collector-api

  collector-api:
    image: otel/opentelemetry-collector:latest
    container_name: collector-api
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - 4317:4317
      - 4318:4318